// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn9wun5g0smlkl5pFex1fSFtA2PfvXdW8',
    appId: '1:993306057340:web:087958760564a8372787f9',
    messagingSenderId: '993306057340',
    projectId: 'chatappvideocallaudiocall',
    authDomain: 'chatappvideocallaudiocall.firebaseapp.com',
    storageBucket: 'chatappvideocallaudiocall.appspot.com',
    measurementId: 'G-LMRG3JFJPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3DJy7RlGkslN_GHlV9R1kuFdZLCDfhjA',
    appId: '1:993306057340:android:cd3218672c9c76792787f9',
    messagingSenderId: '993306057340',
    projectId: 'chatappvideocallaudiocall',
    storageBucket: 'chatappvideocallaudiocall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR4xG1NshvmMVRaPxUmt2V7hDCELBFV4I',
    appId: '1:993306057340:ios:b718f362d953d8582787f9',
    messagingSenderId: '993306057340',
    projectId: 'chatappvideocallaudiocall',
    storageBucket: 'chatappvideocallaudiocall.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR4xG1NshvmMVRaPxUmt2V7hDCELBFV4I',
    appId: '1:993306057340:ios:b718f362d953d8582787f9',
    messagingSenderId: '993306057340',
    projectId: 'chatappvideocallaudiocall',
    storageBucket: 'chatappvideocallaudiocall.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn9wun5g0smlkl5pFex1fSFtA2PfvXdW8',
    appId: '1:993306057340:web:264bb886f654a8582787f9',
    messagingSenderId: '993306057340',
    projectId: 'chatappvideocallaudiocall',
    authDomain: 'chatappvideocallaudiocall.firebaseapp.com',
    storageBucket: 'chatappvideocallaudiocall.appspot.com',
    measurementId: 'G-73876L5HGY',
  );
}
